image: node:8.15.1 # can be upgraded, depending on your node version used

variables:
  HEROKU_API_KEY: "ae775e38-1c25-4a9c-97c8-017e4a77027c"
  HEROKU_APP_NAME: "blood-bank-front-end"

before_script:
  - npm install yarn -g
  - yarn

staging:
  type: deploy
  script:
  - yarn build
  - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  only:
  - development

production:
  type: deploy
  script:
  - yarn build
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
  - git push -f heroku HEAD:master
  only:
  - master